---
version: '3.7'

services:
  thredds-quickstart:
    image: unidata/thredds-docker:4.6.14
    ports:
      - "80:8080"
      - "443:8443"
      - "8443:8443"

  thredds-production:
    image: unidata/thredds-docker:4.6.14
    ports:
      - "80:8080"
      - "443:8443"
      - "8443:8443"
    container_name: thredds
    volumes:
      - /opt/data-thredds-docker/tomcat/logs:/usr/local/tomcat/logs
      - /opt/data-thredds-docker/thredds/logs:/usr/local/tomcat/content/thredds/logs
      - /opt/data-thredds-docker/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - /opt/data-thredds-docker/thredds:/usr/local/tomcat/content/thredds
      - /opt/data-thredds-docker/data/directory1:/path/to/your/data/directory1
      - /opt/data-thredds-docker/data/directory2:/path/to/your/data/directory2
    env_file:
      - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"

  ###
  # TDM
  # Not strictly part of this repo, but useful to have around
  # https://github.com/Unidata/tdm-docker
  ###

  tdm:
    image: unidata/tdm-docker:latest
    container_name: tdm
    volumes:
      - /path/to/your/thredds/directory:/usr/local/tomcat/content/thredds
      - /path/to/your/data/directory1:/path/to/your/data/directory1
      # TDM logging non-configurable until 5.0 so you'll need tdm.sh and
      # tdm.jar if you want to log outside the container :-(
      - /path/to/your/tdm/logs:/usr/local/tomcat/content/tdm/
    env_file:
      - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"
